# Use this file as a starting point to create
# a development setup for working on our Flask API.
#
# Bonus point: simulate production by adding a Load Balancer
# service using Nginx or HAProxy.


version: '3'
services:
  api1:
    build: ./api1
    ports:
    - "5001:5000"
  api2:
    build: ./api2
    ports:
    - "5002:5000"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - api1
      - api2
